# Generated by Django 4.2.3 on 2023-07-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_name',
            field=models.CharField(blank=True, choices=[('b', 'Bitbucket'),
                                   ('gh', 'Github'), ('gl', 'Gitlab')], max_length=2, null=True),
        ),
    ]
