# Generated by Django 4.2.3 on 2025-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dropbox_folder',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_folder',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
