# Generated by Django 4.2.3 on 2023-12-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_owner',
            field=models.CharField(blank=True, choices=[('rg3915', 'rg3915')], max_length=11, null=True),
        ),
    ]
