# Generated by Django 4.2.3 on 2023-09-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_repository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, help_text='Digite a url do repositório', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Digite o título do projeto', max_length=255, unique=True),
        ),
    ]
