# Generated by Django 4.2.3 on 2023-07-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
