# Generated by Django 4.2.3 on 2023-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_label_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='title',
        ),
        migrations.AddField(
            model_name='sprint',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
