# Generated by Django 4.2.3 on 2023-12-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='value',
            new_name='value_total',
        ),
        migrations.AddField(
            model_name='payment',
            name='value_per_hour',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=7),
            preserve_default=False,
        ),
    ]
