# Generated by Django 4.2.3 on 2023-12-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_rename_value_payment_value_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='hours',
        ),
        migrations.AddField(
            model_name='payment',
            name='spent_time_total',
            field=models.DurationField(blank=True, help_text='horas', null=True),
        ),
    ]
